/**
 * Schema — baseline DDL, applied idempotently at boot.
 *
 * Conventions (match the API contract in the frontend's types/pet.ts):
 *   • TEXT primary keys are UUIDs generated by the app.
 *   • Timestamps are ISO-8601 UTC strings (`new Date().toISOString()`),
 *     because the client parses them with `new Date(...)`.
 *   • Dates without time (attendance.date, due_date, joining_date,
 *     scheduled_date) are 'YYYY-MM-DD'.
 *   • Booleans are INTEGER 0/1.
 *   • JSON blobs (payloads, metadata) are TEXT.
 *   • Display names that the UI reads on every list (school_name,
 *     employee_name, assigned_to_user_name, …) are denormalized onto the
 *     row at write time — the screens are list-heavy and this keeps every
 *     endpoint a single query away from being renderable.
 */
'use strict';

const BASELINE_ID = '0001_baseline';

const DDL = `
CREATE TABLE IF NOT EXISTS schema_migrations (
  id TEXT PRIMARY KEY,
  applied_at TEXT NOT NULL
);

-- ── Identity ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  role TEXT NOT NULL CHECK (role IN ('main_admin', 'employee')),
  employee_code TEXT UNIQUE,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
  department TEXT,
  team_id TEXT,
  photo_path TEXT,
  joining_date TEXT,
  must_change_password INTEGER NOT NULL DEFAULT 0,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  family_id TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  revoked_at TEXT,
  created_at TEXT NOT NULL,
  ip TEXT,
  user_agent TEXT
);
CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens(user_id);

-- ── Schools ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS schools (
  id TEXT PRIMARY KEY,
  school_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  address TEXT,
  locality TEXT,
  city TEXT,
  district TEXT,
  state TEXT,
  phone TEXT,
  contact_person_name TEXT,
  contact_person_phone TEXT,
  latitude REAL,
  longitude REAL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  notes TEXT,
  created_by_user_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_schools_status ON schools(status);
CREATE INDEX IF NOT EXISTS idx_schools_name ON schools(name);

-- ── Students ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS students (
  id TEXT PRIMARY KEY,
  pet_student_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  photo_path TEXT,
  dob TEXT,
  age INTEGER,
  gender TEXT CHECK (gender IN ('male', 'female', 'other')),
  student_phone TEXT,
  parent_name TEXT,
  parent_phone TEXT,
  parent_relation TEXT,
  school_id TEXT REFERENCES schools(id) ON DELETE SET NULL,
  school_name TEXT,
  school_address TEXT,
  locality TEXT,
  city TEXT,
  district TEXT,
  state TEXT,
  current_class TEXT,
  previous_school TEXT,
  address TEXT,
  status TEXT NOT NULL DEFAULT 'registered'
    CHECK (status IN ('registered', 'test_scheduled', 'test_completed', 'under_evaluation',
                      'selected', 'waitlisted', 'not_selected', 'enrolled', 'inactive')),
  registration_source TEXT NOT NULL DEFAULT 'field_app',
  registered_by_user_id TEXT NOT NULL REFERENCES users(id),
  registered_by_user_name TEXT NOT NULL DEFAULT '',
  registration_date TEXT NOT NULL,
  intake_id TEXT,
  registered_visit_id TEXT,
  notes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_students_status ON students(status);
CREATE INDEX IF NOT EXISTS idx_students_school ON students(school_id);
CREATE INDEX IF NOT EXISTS idx_students_name ON students(name);
CREATE INDEX IF NOT EXISTS idx_students_parent_phone ON students(parent_phone);
CREATE INDEX IF NOT EXISTS idx_students_student_phone ON students(student_phone);
CREATE INDEX IF NOT EXISTS idx_students_reg_by ON students(registered_by_user_id);

CREATE TABLE IF NOT EXISTS student_status_history (
  id TEXT PRIMARY KEY,
  student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  changed_by_user_id TEXT NOT NULL,
  changed_by_user_name TEXT NOT NULL DEFAULT '',
  reason TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ssh_student ON student_status_history(student_id);

-- ── Field visits ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS field_visits (
  id TEXT PRIMARY KEY,
  school_id TEXT NOT NULL REFERENCES schools(id),
  school_name TEXT NOT NULL DEFAULT '',
  employee_id TEXT NOT NULL REFERENCES users(id),
  employee_name TEXT NOT NULL DEFAULT '',
  purpose TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  started_at TEXT NOT NULL,
  ended_at TEXT,
  start_latitude REAL,
  start_longitude REAL,
  end_latitude REAL,
  end_longitude REAL,
  students_contacted INTEGER NOT NULL DEFAULT 0,
  students_registered INTEGER NOT NULL DEFAULT 0,
  documents_collected INTEGER NOT NULL DEFAULT 0,
  notes TEXT,
  report TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_visits_employee ON field_visits(employee_id, status);
CREATE INDEX IF NOT EXISTS idx_visits_school ON field_visits(school_id);
CREATE INDEX IF NOT EXISTS idx_visits_status ON field_visits(status);

CREATE TABLE IF NOT EXISTS field_media (
  id TEXT PRIMARY KEY,
  visit_id TEXT REFERENCES field_visits(id) ON DELETE CASCADE,
  school_id TEXT REFERENCES schools(id) ON DELETE SET NULL,
  uploaded_by_user_id TEXT NOT NULL REFERENCES users(id),
  uploaded_by_user_name TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL DEFAULT 'photo' CHECK (type IN ('photo', 'document', 'video')),
  relative_path TEXT,
  original_name TEXT,
  caption TEXT,
  status TEXT NOT NULL DEFAULT 'ready' CHECK (status IN ('pending_upload', 'ready')),
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_media_visit ON field_media(visit_id);

CREATE TABLE IF NOT EXISTS student_documents (
  id TEXT PRIMARY KEY,
  student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  uploaded_by_user_id TEXT NOT NULL REFERENCES users(id),
  uploaded_by_user_name TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL DEFAULT 'document' CHECK (type IN ('photo', 'document', 'other')),
  relative_path TEXT,
  original_name TEXT,
  caption TEXT,
  status TEXT NOT NULL DEFAULT 'ready' CHECK (status IN ('pending_upload', 'ready')),
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_docs_student ON student_documents(student_id);

-- ── Tasks ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tasks (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  created_by_user_id TEXT NOT NULL REFERENCES users(id),
  created_by_user_name TEXT NOT NULL DEFAULT '',
  assigned_to_user_id TEXT NOT NULL REFERENCES users(id),
  assigned_to_user_name TEXT NOT NULL DEFAULT '',
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'in_progress', 'submitted', 'completed', 'cancelled')),
  due_date TEXT,
  school_id TEXT,
  student_id TEXT,
  visit_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  completed_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks(assigned_to_user_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_creator ON tasks(created_by_user_id);

CREATE TABLE IF NOT EXISTS task_events (
  id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  actor_user_id TEXT NOT NULL REFERENCES users(id),
  actor_user_name TEXT NOT NULL DEFAULT '',
  event_type TEXT NOT NULL,
  from_status TEXT,
  to_status TEXT,
  note TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_task_events_task ON task_events(task_id);

-- ── Chat ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS conversations (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('direct', 'group')),
  title TEXT,
  created_by_user_id TEXT NOT NULL REFERENCES users(id),
  last_message_at TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_convos_last ON conversations(last_message_at);

CREATE TABLE IF NOT EXISTS conversation_members (
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TEXT NOT NULL,
  last_read_at TEXT,
  PRIMARY KEY (conversation_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_conv_members_user ON conversation_members(user_id);

CREATE TABLE IF NOT EXISTS chat_messages (
  id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id TEXT NOT NULL REFERENCES users(id),
  sender_name TEXT NOT NULL DEFAULT '',
  text TEXT NOT NULL,
  attachment_paths TEXT,
  linked_task_id TEXT,
  linked_student_id TEXT,
  linked_school_id TEXT,
  linked_visit_id TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_messages_convo ON chat_messages(conversation_id, created_at);

-- ── Attendance ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS attendance (
  id TEXT PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  employee_name TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL,
  check_in_at TEXT,
  check_out_at TEXT,
  status TEXT NOT NULL DEFAULT 'present'
    CHECK (status IN ('present', 'absent', 'leave', 'half_day', 'late')),
  latitude REAL,
  longitude REAL,
  remarks TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (employee_id, date)
);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(date);

-- ── Tests ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tests (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  passing_percentage REAL NOT NULL DEFAULT 50,
  scheduled_date TEXT,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'scheduled', 'completed', 'finalized')),
  created_by_user_id TEXT NOT NULL REFERENCES users(id),
  created_by_user_name TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tests_status ON tests(status);

CREATE TABLE IF NOT EXISTS test_subjects (
  id TEXT PRIMARY KEY,
  test_id TEXT NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  max_marks REAL NOT NULL,
  passing_marks REAL,
  sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_subjects_test ON test_subjects(test_id);

CREATE TABLE IF NOT EXISTS test_assignments (
  id TEXT PRIMARY KEY,
  test_id TEXT NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'assigned'
    CHECK (status IN ('assigned', 'absent', 'finalized')),
  finalized_at TEXT,
  decision TEXT CHECK (decision IN ('selected', 'waitlisted', 'not_selected')),
  decision_remarks TEXT,
  created_at TEXT NOT NULL,
  UNIQUE (test_id, student_id)
);
CREATE INDEX IF NOT EXISTS idx_assign_test ON test_assignments(test_id);
CREATE INDEX IF NOT EXISTS idx_assign_student ON test_assignments(student_id);

CREATE TABLE IF NOT EXISTS test_marks (
  id TEXT PRIMARY KEY,
  assignment_id TEXT NOT NULL REFERENCES test_assignments(id) ON DELETE CASCADE,
  subject_id TEXT NOT NULL REFERENCES test_subjects(id) ON DELETE CASCADE,
  obtained_marks REAL NOT NULL,
  UNIQUE (assignment_id, subject_id)
);

-- ── Enrollment ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS enrollments (
  id TEXT PRIMARY KEY,
  student_id TEXT NOT NULL UNIQUE REFERENCES students(id) ON DELETE CASCADE,
  stage TEXT NOT NULL DEFAULT 'follow_up'
    CHECK (stage IN ('follow_up', 'documents', 'verification', 'enrolled')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'withdrawn')),
  notes TEXT,
  started_by_user_id TEXT NOT NULL REFERENCES users(id),
  started_by_user_name TEXT NOT NULL DEFAULT '',
  verified_by_user_id TEXT,
  enrolled_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- ── Website forms ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS website_form_submissions (
  id TEXT PRIMARY KEY,
  form_type TEXT NOT NULL DEFAULT 'enquiry'
    CHECK (form_type IN ('student_registration', 'enquiry', 'volunteer', 'school_partnership', 'contact')),
  name TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  email TEXT,
  payload TEXT,
  status TEXT NOT NULL DEFAULT 'new'
    CHECK (status IN ('new', 'assigned', 'in_progress', 'converted', 'closed')),
  assigned_to_user_id TEXT REFERENCES users(id),
  assigned_to_user_name TEXT,
  converted_student_id TEXT REFERENCES students(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_forms_status ON website_form_submissions(status);

-- ── Notifications / audit / sync / settings ─────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL DEFAULT 'info',
  is_read INTEGER NOT NULL DEFAULT 0,
  link_type TEXT,
  link_id TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, is_read);

CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  actor_type TEXT,
  actor_id TEXT,
  actor_label TEXT,
  action TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  metadata TEXT,
  ip TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);

CREATE TABLE IF NOT EXISTS sync_idempotency (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  idempotency_key TEXT NOT NULL,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  result TEXT,
  created_at TEXT NOT NULL,
  UNIQUE (user_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS organization_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS counters (
  name TEXT PRIMARY KEY,
  value INTEGER NOT NULL DEFAULT 0
);
`;

/** Apply the baseline schema. Safe to call on every boot. */
function migrate(db) {
  db.exec(DDL);
  const applied = db.prepare('SELECT 1 AS x FROM schema_migrations WHERE id = ?').get(BASELINE_ID);
  if (!applied) {
    db.prepare('INSERT INTO schema_migrations (id, applied_at) VALUES (?, ?)').run(
      BASELINE_ID,
      new Date().toISOString(),
    );
  }
}

module.exports = { migrate, BASELINE_ID };
